### Matrizes com numpy

In [1]:
import numpy as np

In [2]:
mat1 = [[2,3],[4,5],[7,8]]
mat1 = np.asmatrix(mat1)

In [3]:
type(mat1)

numpy.matrixlib.defmatrix.matrix

In [4]:
mat1

matrix([[2, 3],
        [4, 5],
        [7, 8]])

In [5]:
mat1[:,1]

matrix([[3],
        [5],
        [8]])

In [6]:
mat1[0,:]

matrix([[2, 3]])

In [7]:
mat2 = [[2,3],[5,6],[8,7]] #criando a segunda matriz
mat2 = np.asmatrix(mat2)

In [8]:
mat2

matrix([[2, 3],
        [5, 6],
        [8, 7]])

In [9]:
np.transpose(mat2) # transposta da mat1

matrix([[2, 5, 8],
        [3, 6, 7]])

In [10]:
mult = np.transpose(mat2) * mat1
mult

matrix([[80, 95],
        [79, 95]])

In [11]:
np.linalg.det(mult) # determinante ((80*95)-(95*79))

95.0

In [12]:
np.linalg.pinv(mult) # pseudo-inverse

matrix([[ 1.        , -1.        ],
        [-0.83157895,  0.84210526]])

In [13]:
np.linalg.inv(mult) # inversa

matrix([[ 1.        , -1.        ],
        [-0.83157895,  0.84210526]])

In [14]:
vec = [2,3] # criando um vetor

In [15]:
np.dot(mult,vec) # multiplicando vetor com matriz

matrix([[445, 443]])

#### Criar uma função soma 

In [16]:
def somar(m1, m2):
    matriz_soma = []
    # Supondo que as duas matrizes possuem o mesmo tamanho
    quant_linhas = len(m1) # Conta quantas linhas existem
    quant_colunas = len(m1[0]) # Conta quantos elementos têm em uma linha
    for i in range(quant_linhas):
        # Cria uma nova linha na matriz_soma
        matriz_soma.append([])
        for j in range(quant_colunas):
            # Somando os elementos que possuem o mesmo índice
            soma = m1[i][j] + m2[i][j]
            matriz_soma[i].append(soma)
    return matriz_soma