## Fazer a soma de duas matrizes

In [1]:
import numpy as np

In [2]:
mat1=np.array([[2,3],[4,5],[7,8]])

In [3]:
mat1 #olhar como fica

array([[2, 3],
       [4, 5],
       [7, 8]])

In [4]:
type(mat1) #olhar o tipo

numpy.ndarray

In [5]:
mat1[:,1]

array([3, 5, 8])

In [6]:
mat1[0,:]

array([2, 3])

In [7]:
mat2=np.array([[2,3],[5,6],[8,7]]) #criando a segunda matriz

#### Criar uma função soma 

In [8]:
def somar(m1, m2):
    matriz_soma = []
    # Supondo que as duas matrizes possuem o mesmo tamanho
    quant_linhas = len(m1) # Conta quantas linhas existem
    quant_colunas = len(m1[0]) # Conta quantos elementos têm em uma linha
    for i in range(quant_linhas):
        # Cria uma nova linha na matriz_soma
        matriz_soma.append([])
        for j in range(quant_colunas):
            # Somando os elementos que possuem o mesmo índice
            soma = m1[i][j] + m2[i][j]
            matriz_soma[i].append(soma)
    return matriz_soma

In [9]:
mat1

array([[2, 3],
       [4, 5],
       [7, 8]])

In [10]:
mat2

array([[2, 3],
       [5, 6],
       [8, 7]])

In [11]:
type(mat2)

numpy.ndarray

In [12]:
somamat=somar(mat1,mat2)
somamat

[[4, 6], [9, 11], [15, 15]]

In [13]:
type(somamat) #virou lista 

list

In [14]:
somamat=np.array(somamat) #transfomando em matriz novamente 
type(somamat)

numpy.ndarray

In [15]:
somamat

array([[ 4,  6],
       [ 9, 11],
       [15, 15]])

#### Poderiamos ter feito uma soma simples (sem criar fórmula)

In [16]:
mat1+mat2

array([[ 4,  6],
       [ 9, 11],
       [15, 15]])

## Fazer a média

In [17]:
mat1

array([[2, 3],
       [4, 5],
       [7, 8]])

In [18]:
mat2

array([[2, 3],
       [5, 6],
       [8, 7]])

In [19]:
(mat1+mat2)/2

array([[ 2. ,  3. ],
       [ 4.5,  5.5],
       [ 7.5,  7.5]])