### Calcular SVD 

In [1]:
import numpy as np

In [2]:
A = [[0.95,0.49,0.46,0.44],[0.23,0.89,0.02,0.62],[0.61,0.76,0.82,0.79]]
A = np.asmatrix(A)
A

matrix([[ 0.95,  0.49,  0.46,  0.44],
        [ 0.23,  0.89,  0.02,  0.62],
        [ 0.61,  0.76,  0.82,  0.79]])

In [3]:
u,s,v = np.linalg.svd(A)

In [4]:
np.around(u,decimals=2) # u

array([[-0.55, -0.54, -0.64],
       [-0.45,  0.84, -0.31],
       [-0.7 , -0.11,  0.71]])

In [5]:
s 

array([ 2.1043236 ,  0.6686618 ,  0.38537461])

In [6]:
np.around(v.transpose(),decimals=2) # v

array([[-0.5 , -0.58, -0.64,  0.06],
       [-0.57,  0.59, -0.14, -0.55],
       [-0.4 , -0.48,  0.72, -0.29],
       [-0.51,  0.29,  0.22,  0.78]])

u = autovetores de AA*

s = valores singulares de A, ou seja, raíz dos autovalores de $A^{T}A$

v = autovetores de A*A

In [7]:
A*A.T

matrix([[ 1.5478,  0.9366,  1.6767],
        [ 0.9366,  1.2298,  1.3229],
        [ 1.6767,  1.3229,  2.2462]])

In [8]:
np.linalg.eig(A*A.T)

(array([ 4.4281778 ,  0.14851359,  0.44710861]),
 matrix([[-0.55397885, -0.63675961,  0.53632512],
         [-0.45152837, -0.31143091, -0.83614169],
         [-0.69944947,  0.70537082,  0.11498889]]))

In [9]:
A.T*A

matrix([[ 1.3275,  1.1338,  0.9418,  1.0425],
        [ 1.1338,  1.6098,  0.8664,  1.3678],
        [ 0.9418,  0.8664,  0.8844,  0.8626],
        [ 1.0425,  1.3678,  0.8626,  1.2021]])

In [10]:
np.linalg.eig(A.T*A)

(array([  4.42817780e+00,   4.47108608e-01,   1.48513590e-01,
          2.39646191e-16]),
 matrix([[ 0.50220205,  0.57927564,  0.63905231,  0.06200793],
         [ 0.57257899, -0.58919956,  0.13779811, -0.55318067],
         [ 0.39794707,  0.48496505, -0.72466122, -0.2851546 ],
         [ 0.51145336, -0.2865179 , -0.21792187,  0.78027752]]))

Questão 3) Verificação de Conceitos - Lista 6

In [11]:
A = [[5,0,0],[0,2,0]]
A = np.asmatrix(A)
A

matrix([[5, 0, 0],
        [0, 2, 0]])

In [13]:
u,s,v = np.linalg.svd(A)

In [14]:
u

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [15]:
s

array([ 5.,  2.])

In [16]:
v.T

matrix([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])